//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTrans.GlyphLoader.TestFonts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GraphResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterTrans.GlyphLoader.TestFonts.GraphResources", typeof(GraphResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rect x=&quot;{0}&quot; y=&quot;{1}&quot; width=&quot;{2}&quot; height=&quot;{3}&quot; stroke=&quot;orange&quot; stroke-width=&quot;1&quot;  fill=&quot;transparent&quot; /&gt;.
        /// </summary>
        public static string AdvanceBox {
            get {
                return ResourceManager.GetString("AdvanceBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;line x1=&quot;0&quot; y1=&quot;{0}&quot; x2=&quot;400&quot; y2=&quot;{0}&quot; style=&quot;stroke:red;stroke-width:2&quot; /&gt;.
        /// </summary>
        public static string Baseline {
            get {
                return ResourceManager.GetString("Baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rect x=&quot;{0}&quot; y=&quot;{1}&quot; width=&quot;{2}&quot; height=&quot;{3}&quot; stroke=&quot;navy&quot; stroke-width=&quot;1&quot;  fill=&quot;transparent&quot; /&gt;.
        /// </summary>
        public static string BlackBox {
            get {
                return ResourceManager.GetString("BlackBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;circle cx=&quot;{0}&quot; cy=&quot;{1}&quot; r=&quot;2&quot; stroke-width=&quot;0&quot; fill=&quot;blue&quot; cursor=&quot;pointer&quot;&gt;
        ///  &lt;title&gt;({2},{3})&lt;/title&gt;
        ///&lt;/circle&gt;.
        /// </summary>
        public static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;circle cx=&quot;{0}&quot; cy=&quot;{1}&quot; r=&quot;2&quot; stroke-width=&quot;0&quot; fill=&quot;black&quot; cursor=&quot;pointer&quot;&gt;
        ///  &lt;title&gt;({2},{3})&lt;/title&gt;
        ///&lt;/circle&gt;.
        /// </summary>
        public static string CurvePoint {
            get {
                return ResourceManager.GetString("CurvePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; version=&quot;1.0&quot; width=&quot;400&quot; height=&quot;400&quot; id=&quot;svg2180&quot;&gt;
        ///  &lt;defs id=&quot;defs2182&quot;/&gt;
        ///  &lt;g style=&quot;opacity:1;display:inline&quot; id=&quot;layer1&quot;&gt;
        ///    &lt;g style=&quot;stroke:#a9a9a9;stroke-opacity:1&quot; id=&quot;g8191&quot;&gt;
        ///      &lt;path d=&quot;M 20,0 L 20,400&quot; style=&quot;fill:none;fill-rule:evenodd;stroke:#a9a9a9;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;circle cx=&quot;{0}&quot; cy=&quot;{1}&quot; r=&quot;2&quot; stroke=&quot;black&quot; stroke-width=&quot;1&quot; fill=&quot;transparent&quot; cursor=&quot;pointer&quot;&gt;
        ///  &lt;title&gt;({2},{3})&lt;/title&gt;
        ///&lt;/circle&gt;.
        /// </summary>
        public static string OriginPoint {
            get {
                return ResourceManager.GetString("OriginPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path transform=&quot;translate({1},{2})&quot; d=&quot;{0}&quot; fill=&quot;transparent&quot; stroke=&quot;black&quot; stroke-width=&quot;1&quot; /&gt;.
        /// </summary>
        public static string StrokePath {
            get {
                return ResourceManager.GetString("StrokePath", resourceCulture);
            }
        }
    }
}
