//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTrans.GlyphLoader.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterTrans.GlyphLoader.Tests.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;style&gt;dt {{ font-weight: bold; }} svg {{ border: 1px solid #000; }}&lt;/style&gt;&lt;/head&gt;
        ///&lt;body&gt;&lt;h1&gt;Glyph comparison view&lt;/h1&gt;
        ///&lt;dl&gt;&lt;dt&gt;File: &lt;/dt&gt;&lt;dd&gt;{0}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;GlyphIndex: &lt;/dt&gt;&lt;dd&gt;{1}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;Typeface: &lt;/dt&gt;&lt;dd&gt;{2}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;GlyphTypeface: &lt;/dt&gt;&lt;dd&gt;{3}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string GlyphComparison {
            get {
                return ResourceManager.GetString("GlyphComparison", resourceCulture);
            }
        }
    }
}
