//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTrans.GlyphLoader.Tests {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterTrans.GlyphLoader.Tests.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;rect x=&quot;{0}&quot; y=&quot;{1}&quot; width=&quot;{2}&quot; height=&quot;{3}&quot; stroke=&quot;orange&quot; stroke-width=&quot;1&quot;  fill=&quot;transparent&quot; /&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdvanceBox {
            get {
                return ResourceManager.GetString("AdvanceBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;rect x=&quot;{0}&quot; y=&quot;{1}&quot; width=&quot;{2}&quot; height=&quot;{3}&quot; stroke=&quot;black&quot; stroke-width=&quot;1&quot;  fill=&quot;transparent&quot; /&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlackBox {
            get {
                return ResourceManager.GetString("BlackBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;circle cx=&quot;{0}&quot; cy=&quot;{1}&quot; r=&quot;2&quot; stroke-width=&quot;0&quot; fill=&quot;blue&quot; cursor=&quot;pointer&quot;&gt;
        ///  &lt;title&gt;({2},{3})&lt;/title&gt;
        ///&lt;/circle&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;circle cx=&quot;{0}&quot; cy=&quot;{1}&quot; r=&quot;2&quot; stroke-width=&quot;0&quot; fill=&quot;black&quot; cursor=&quot;pointer&quot;&gt;
        ///  &lt;title&gt;({2},{3})&lt;/title&gt;
        ///&lt;/circle&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurvePoint {
            get {
                return ResourceManager.GetString("CurvePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;style&gt;dt {{ font-weight: bold; }} svg {{ border: 1px solid #000; }}&lt;/style&gt;&lt;/head&gt;
        ///&lt;body&gt;&lt;h1&gt;Glyph comparison view&lt;/h1&gt;
        ///&lt;dl&gt;&lt;dt&gt;File: &lt;/dt&gt;&lt;dd&gt;{0}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;GlyphIndex: &lt;/dt&gt;&lt;dd&gt;{1}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;Typeface: &lt;/dt&gt;&lt;dd&gt;{2}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;GlyphTypeface: &lt;/dt&gt;&lt;dd&gt;{3}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;/body&gt;&lt;/html&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlyphComparison {
            get {
                return ResourceManager.GetString("GlyphComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; version=&quot;1.0&quot; width=&quot;400&quot; height=&quot;400&quot; id=&quot;svg2180&quot;&gt;
        ///  &lt;defs id=&quot;defs2182&quot;/&gt;
        ///  &lt;g style=&quot;opacity:1;display:inline&quot; id=&quot;layer1&quot;&gt;
        ///    &lt;g style=&quot;stroke:#a9a9a9;stroke-opacity:1&quot; id=&quot;g8191&quot;&gt;
        ///      &lt;path d=&quot;M 20,0 L 20,400&quot; style=&quot;fill:none;fill-rule:evenodd;stroke:#a9a9a9;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GraphPaper {
            get {
                return ResourceManager.GetString("GraphPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;circle cx=&quot;{0}&quot; cy=&quot;{1}&quot; r=&quot;2&quot; stroke=&quot;black&quot; stroke-width=&quot;1&quot; fill=&quot;transparent&quot; cursor=&quot;pointer&quot;&gt;
        ///  &lt;title&gt;({2},{3})&lt;/title&gt;
        ///&lt;/circle&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OriginPoint {
            get {
                return ResourceManager.GetString("OriginPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;path transform=&quot;translate({1},{2})&quot; d=&quot;{0}&quot; fill=&quot;transparent&quot; stroke=&quot;black&quot; stroke-width=&quot;1&quot; /&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StrokePath {
            get {
                return ResourceManager.GetString("StrokePath", resourceCulture);
            }
        }
    }
}
